defaults: &defaults
  working_directory: ~/magento
  environment:
    MDE_COMPOSER_MODULE: magentojapan/common
    MDE_COMPOSER_METAPACKAGE: magentojapan/common
    CORE_GIT_REPOSITORY: magento/magento2
    CORE_GIT_BRANCH: 2.3-develop
  docker:
    - image: ishakhsuvarov/mde-testing:latest

version: 2

jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: Cloning Magento 2.3-develop
          command: git clone https://github.com/$CORE_GIT_REPOSITORY.git --depth 1 --single-branch --branch $CORE_GIT_BRANCH .

      - checkout:
          path: mde

      - restore_cache:
          keys:
            - magento-dependencies-{{ checksum "composer.lock" }}-v1

      - run:
          name: Installing dependencies
          command: composer install -n

      - save_cache:
          key: magento-dependencies-{{ checksum "composer.lock" }}-v1
          paths:
            - "vendor"

      - run:
          name: Installing MDE
          command: |
            composer config minimum-stability dev
            composer config repositories.metapackage path "./*"
            composer config repositories.modules path "./*/*/"
            composer require $MDE_COMPOSER_METAPACKAGE

      - persist_to_workspace:
          root: .
          paths:
            - .

  unit_test:
    <<: *defaults
    steps:

      - attach_workspace:
          at: .

      - run:
          name: Unit Test
          command: ./vendor/phpunit/phpunit/phpunit -c dev/tests/unit -dmemory_limit=2G

  static_test:
    <<: *defaults
    steps:

      - attach_workspace:
          at: .

      - run:
          name: Prepare file list
          command: |
            find mde -not -path '*/.*/*' -not -name '.*' -type f -follow -print > dev/tests/static/testsuite/Magento/Test/_files/changed_files_mde.txt
            find mde -not -path '*/.*/*' -not -name '.*' -type f -follow -print > dev/tests/static/testsuite/Magento/Test/_files/changed_files_mde.added.txt
            echo "$MDE_COMPOSER_MODULE" > dev/tests/static/testsuite/Magento/Test/Integrity/_files/blacklist/composer_root_modules_mde.txt

      - run:
          name: Static test
          command: ./vendor/phpunit/phpunit/phpunit -c dev/tests/static -dmemory_limit=2G

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - unit_test:
          requires:
            - build
      - static_test:
          requires:
            - build
